spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projecttracker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/auditlogs

  cache:
    type: simple

server:
  port: 8080
